---
include:
  - board: nice_nano//zmk
    shield: voyager_ps_left
  - board: nice_nano//zmk
    shield: voyager_ps_right
  - board: nice_nano//zmk
    shield: voyager_ps_left nice_view_adapter nice_view
    artifact-name: voyager_ps_left_niceview
  - board: nice_nano//zmk
    shield: voyager_ps_right nice_view_adapter nice_view
    artifact-name: voyager_ps_right_niceview
  - board: nice_nano//zmk
    shield: settings_reset
    artifact-name: settings_reset
